version: "3"

#x-volumes: &docker-volumes
#  - "~/.sbt:/root/.sbt"
#  - "~/Library/Caches/Coursier:/root/.cache/coursier" # MacOS Coursier cache
#  #      - "~/.cache/coursier:/root/.cache/coursier" # Linux Coursier cache
#  #      - "~/AppData/Local/Coursier/Cache:/root/.cache/coursier" # Windows Coursier cache
#  - ".:/opt/video-downloader-back-end"
#  - "/opt/video-downloader-back-end/project/target"
#  - "/opt/video-downloader-back-end/migration-application/target"
#  - "/opt/video-downloader-back-end/core/target"
#  - "/opt/video-downloader-back-end/api/target"
#  - "/opt/video-downloader-back-end/batch/target"
#  - "/root/.sbt/1.0/plugins"
#  - "./videos:/opt/videos"
#  - "./images:/opt/images"

x-volumes: &docker-volumes
  - "./videos:/opt/videos"
  - "./images:/opt/images"

services:
  nginx:
    image: nginx
    depends_on:
      - api
    ports:
      - 443:443
    volumes:
      - "./nginx/ssl:/etc/ssl"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

  api:
    image: video-downloader-api:latest
#    build: .
#    command: api/run
    depends_on:
      postgres:
        condition: service_healthy
      migration-application:
        condition: service_completed_successfully
      redis:
        condition: service_started
    ports:
      - 8000:8000
#      - 5005:5005
    volumes: *docker-volumes
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "redis-password"
      KAFKA_BROKERS: "kafka-cluster:9092"
      SCHEMA_REGISTRY: "http://kafka-cluster:8081"
      VIDEO_FOLDER: "/opt/videos/downloads"
      IMAGE_FOLDER: "/opt/images"

  batch:
    image: video-downloader-batch:latest
#    build: .
#    command: batch/run
    depends_on:
      postgres:
        condition: service_healthy
      migration-application:
        condition: service_completed_successfully
      redis:
        condition: service_started
#    ports:
#      - 5006:5005
    volumes: *docker-volumes
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "redis-password"
      KAFKA_BROKERS: "kafka-cluster:9092"
      SCHEMA_REGISTRY: "http://kafka-cluster:8081"
      VIDEO_FOLDER: "/opt/videos/downloads"
      OTHER_VIDEO_FOLDERS: "/opt/videos/location-1;/opt/videos/location-2;/opt/videos/location-3"
      IMAGE_FOLDER: "/opt/images"

  migration-application:
    image: video-downloader-migration-application:latest
#    build: .
#    command: migrationApplication/run
    depends_on:
      postgres:
        condition: service_healthy
#    ports:
#      - 5007:5005
    volumes: *docker-volumes
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"

  postgres:
    image: postgres
#    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d video-downloader" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "video-downloader"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

  redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: "redis-password"

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    ports:
#      - 8001:80
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "me@ruchij.com"
#      PGADMIN_DEFAULT_PASSWORD: "password"

  kafka-cluster:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: kafka-cluster
      RUNTESTS: 0
      FORWARDLOGS: 0
      SAMPLEDATA: 0
    ports:
      - 3030:3030