version: "3"

services:

  api:
    image: video-downloader-api:latest
    depends_on:
      - migration-application
      - redis
    ports:
      - 8000:8000
    volumes:
      - "./videos:/opt/videos"
      - "./images:/opt/images"
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "redis-password"
      VIDEO_FOLDER: "/opt/videos"
      IMAGE_FOLDER: "/opt/images"

  batch:
    image: video-downloader-batch:latest
    depends_on:
      - migration-application
      - redis
    volumes:
      - "./videos:/opt/videos"
      - "./images:/opt/images"
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "redis-password"
      VIDEO_FOLDER: "/opt/videos"
      IMAGE_FOLDER: "/opt/images"

  migration-application:
    image: video-downloader-migration-application:latest
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"

  postgres:
    image: postgres
#    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "video-downloader"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

  redis:
    image: bitnami/redis
    ports:
      - 6378:6379
    environment:
      REDIS_PASSWORD: "redis-password"

#  front-end:
#    image: video-downloader-front-end:latest
#    ports:
#      - 80:80
