version: "3"

services:

  web:
    image: video-downloader-web:latest
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - "./videos:/opt/videos"
      - "./images:/opt/images"
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
      VIDEO_FOLDER: "/opt/videos"
      IMAGE_FOLDER: "/opt/images"

  batch:
    image: video-downloader-batch:latest
    depends_on:
      - postgres
    volumes:
      - "./videos:/opt/videos"
      - "./images:/opt/images"
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
      VIDEO_FOLDER: "/opt/videos"
      IMAGE_FOLDER: "/opt/images"

  postgres:
    image: postgres
#    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "video-downloader"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
