version: "3.8"

x-batch: &batch-app
  image: video-downloader-batch:latest
  depends_on:
    postgres:
      condition: service_healthy
    migration-application:
      condition: service_completed_successfully
    redis:
      condition: service_started
  volumes:
    - "./videos:/opt/videos"
    - "./images:/opt/images"
    - "./batch/src/main/resources/logback.xml:/opt/data/logback.xml"
  environment:
    DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader"
    DATABASE_USER: "admin"
    DATABASE_PASSWORD: "password"
    REDIS_HOSTNAME: "redis"
    REDIS_PORT: "6379"
    REDIS_PASSWORD: "redis-password"
    KAFKA_BROKERS: "kafka-cluster:9092"
    SCHEMA_REGISTRY: "http://kafka-cluster:8081"
    VIDEO_FOLDER: "/opt/videos"
    IMAGE_FOLDER: "/opt/images"

services:
  nginx:
    image: nginx
    depends_on:
      - api
    ports:
      - 8443:443
    volumes:
      - "./nginx/ssl:/etc/ssl"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

  api:
    image: video-downloader-api:latest
    depends_on:
      postgres:
        condition: service_healthy
      migration-application:
        condition: service_completed_successfully
      redis:
        condition: service_started
    ports:
      - 8000:8000
    volumes:
      - "./videos:/opt/videos"
      - "./images:/opt/images"
      - "./api/src/main/resources/logback.xml:/opt/data/logback.xml"
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "redis-password"
      KAFKA_BROKERS: "kafka-cluster:9092"
      SCHEMA_REGISTRY: "http://kafka-cluster:8081"
      VIDEO_FOLDER: "/opt/videos"
      IMAGE_FOLDER: "/opt/images"

  batch-1:
    *batch-app

  batch-2:
    *batch-app

  migration-application:
    image: video-downloader-migration-application:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"

  postgres:
    image: postgres
#    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d video-downloader" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "video-downloader"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

  redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: "redis-password"

  kafka-cluster:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: kafka-cluster
      USER: admin
      PASSWORD: Passw0rd
    ports:
      - 3030:3030