apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: confluent-control-center-certificate
  namespace: {{ namespace }}
spec:
  secretName: confluent-control-center-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ confluent_control_center_hostname }}