apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-control-center-http-auth-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: confluent-control-center-http-auth
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: confluent-control-center-http-auth
        branch: {{ git_branch }}
    spec:
      containers:
        - name: confluent-control-center-http-auth-container
          image: ruchira088/http-auth:latest
          envFrom:
            - configMapRef:
                name: confluent-control-center-http-auth-config-map
            - secretRef:
                name: confluent-control-center-http-auth-secrets
          ports:
            - name: http4s-port
              containerPort: 8000
          readinessProbe:
            httpGet:
              port: http4s-port
              path: /health
          livenessProbe:
            httpGet:
              port: http4s-port
              path: /health
          startupProbe:
            periodSeconds: 5
            failureThreshold: 10
            httpGet:
              port: http4s-port
              path: /health

