apiVersion: v1
kind: Secret
metadata:
  name: confluent-control-center-http-auth-secrets
  namespace: {{ namespace }}
type: Opaque
stringData:
{% for key, value in confluent_control_center_http_auth.secrets.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}