apiVersion: v1
kind: Service
metadata:
  name: confluent-control-center-http-auth-service
  namespace: {{ namespace }}
spec:
  selector:
    app: confluent-control-center-http-auth
    branch: {{ git_branch }}
  ports:
    - name: http4s-port
      port: 8000