apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: video-downloader-api-{{ git_branch }}
spec:
  selector:
    matchLabels:
      app: web
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        branch: {{ git_branch }}
    spec:
      containers:
        - name: web-container
          image: {{ docker_registry }}/video-downloader-web:{{ git_commit }}
          envFrom:
            - configMapRef:
                name: web-config-map
            - secretRef:
                name: web-secrets
          readinessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-readiness-probe
          startupProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-startup-probe
          ports:
            - name: http4s-port
              containerPort: 8000
          volumeMounts:
            - mountPath: {{ web.config_values.VIDEO_FOLDER }}
              name: video-folder
            - mountPath: {{ web.config_values.IMAGE_FOLDER }}
              name: image-folder
      volumes:
        - name: video-folder
          hostPath:
            path: {{ host_video_folder }}
            type: Directory
        - name: image-folder
          hostPath:
            path: {{ host_image_folder }}
            type: Directory
