- name: Print start message
  debug:
    msg: Started building {{ app_name }}

- name: Create output directory
  file:
    path: docker-output
    state: directory

- name: Clean and build sbt project
  shell: cd ../ && sbt clean {{ sbt_project }}/Universal/packageZipTarball

- name: Gather git information
  import_tasks: git-info.yml

- name: Generate the Dockerfile
  template:
    src: docker/apps/{{ docker_file }}
    dest: docker-output/Dockerfile-{{ app_name }}
  vars:
    build_timestamp: "{{ ansible_date_time.iso8601 }}"

- name: Build Docker image
  when: not publish
  shell: |
    docker build \
      -f docker-output/Dockerfile-{{ app_name }} \
      -t ghcr.io/ruchira088/video-downloader-{{ app_name }}:{{ git_branch }} \
      -t ghcr.io/ruchira088/video-downloader-{{ app_name }}:{{ git_branch }}-{{ git_commit }} \
      ../{{ app_name }}/target/universal/

- name: Build and publish Docker image
  when: publish
  block:
    - name: Login to GitHub container registry
      command: docker login ghcr.io -u USERNAME -p {{ access_token }}
      vars:
        access_token: "{{ lookup('aws_ssm', '/github/packages/read-write-token', region='ap-southeast-2') }}"

    - name: Publish Docker image
      shell: |
        docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          -t ghcr.io/ruchira088/video-downloader-{{ app_name }}:{{ git_branch }} \
          -t ghcr.io/ruchira088/video-downloader-{{ app_name }}:{{ git_branch }}-{{ git_commit }} \
          -f docker-output/Dockerfile-{{ app_name }} \
          ../{{ app_name }}/target/universal/

- name: Clean up output directory
  file:
    path: docker-output
    state: absent

- name: Print finish message
  debug:
    msg: Completed building {{ app_name }}