- name: Print start message
  debug:
    msg: Started building DB backup

- name: Create output directory
  file:
    path: docker-output
    state: directory

- name: Gather git information
  import_tasks: git-info.yml

- name: Generate the Dockerfile
  template:
    src: docker/apps/Dockerfile-db-{{ db_operation }}.j2
    dest: docker-output/Dockerfile-db-{{ db_operation }}
  vars:
    build_timestamp: "{{ ansible_date_time.iso8601 }}"

- name: Build Docker image
  when: not publish
  shell: |
    docker build \
      -f docker-output/Dockerfile-db-{{ db_operation }} \
      -t ghcr.io/ruchira088/video-downloader-db-{{ db_operation }}:{{ git_branch }} \
      -t ghcr.io/ruchira088/video-downloader-db-{{ db_operation }}:{{ git_branch }}-{{ git_commit }} \
      ../db-{{ db_operation }}

- name: Build and publish Docker image
  when: publish
  block:
    - name: Login to GitHub container registry
      command: docker login ghcr.io -u USERNAME -p {{ access_token }}
      vars:
        access_token: "{{ lookup('aws_ssm', '/github/packages/read-write-token', region='ap-southeast-2') }}"

    - name: Publish Docker image
      shell: |
        docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          -t ghcr.io/ruchira088/video-downloader-db-{{ db_operation }}:{{ git_branch }} \
          -t ghcr.io/ruchira088/video-downloader-db-{{ db_operation }}:{{ git_branch }}-{{ git_commit }} \
          -f docker-output/Dockerfile-db-{{ db_operation }} \
          ../db-{{ db_operation }}

- name: Clean up output directory
  file:
    path: docker-output
    state: absent

- name: Print finish message
  debug:
    msg: Completed building DB backup