- name: Build DB migration Docker image
  import_tasks: build-docker.yml
  vars:
    sbt_project: migrationApplication
    app_name: migration-application

- name: Build api Docker image
  import_tasks: build-docker.yml
  vars:
    sbt_project: api
    app_name: api
    ports: 8000

- name: Build batch Docker image
  import_tasks: build-docker.yml
  vars:
    sbt_project: batch
    app_name: batch