- name: Gather git information
  import_tasks: git-info.yml

- set_fact:
    config_values:
      production:
        fallback_api_url: https://fallback-api.video.dev.ruchij.com
        database_url: 192.168.0.226:5431/video-downloader
        database_jdbc_url: jdbc:postgresql://192.168.0.226:5431/video-downloader
        redis_hostname: 192.168.0.226
        redis_port: 6380
        kafka_topic_prefix: prod
      development:
        fallback_api_url: "{{ 'https://' + git_branch  + '.fallback-api.video.dev.ruchij.com' }}"
        database_url: 192.168.0.226:5432/video-downloader
        database_jdbc_url: jdbc:postgresql://192.168.0.226:5432/video-downloader
        redis_hostname: 192.168.0.226
        redis_port: 6379
        kafka_topic_prefix: "{{ git_branch }}"
      video_folder: /home/videos
      other_video_folders: ""
      image_folder: /home/images
      kafka_brokers: 192.168.0.226:9092
      schema_registry_url: http://192.168.0.226:8081
      spa_renderer_url: http://spa-renderer-service:8000
    secrets:
      database_user: "{{ lookup('aws_ssm', '/video-downloader/' + env + '/database/user', region='ap-southeast-2') }}"
      database_password: "{{ lookup('aws_ssm', '/video-downloader/' + env + '/database/password', region='ap-southeast-2') }}"
      redis_password: "{{ lookup('aws_ssm', '/video-downloader/' + env + '/redis/password', region='ap-southeast-2')}}"
      api_hashed_password: "{{ lookup('aws_ssm', '/video-downloader/' + env + '/api/hashed-password', region='ap-southeast-2') }}"
      aws_access_key_id: "{{ lookup('aws_ssm', '/video-downloader/shared/backup-creator/access-key-id', region='ap-southeast-2') }}"
      aws_secret_access_key: "{{ lookup('aws_ssm', '/video-downloader/shared/backup-creator/secret-access-key', region='ap-southeast-2') }}"
      fallback_api_admin_token: "{{ lookup('aws_ssm', '/video-downloader/' + env + '/fallback/admin-bearer-token', region='ap-southeast-2') }}"

- set_fact:
    api:
      config_values:
        IMAGE_FOLDER: "{{ config_values.image_folder }}"
        DATABASE_URL: "{{ config_values[env].database_jdbc_url }}"
        REDIS_HOSTNAME: "{{ config_values[env].redis_hostname }}"
        REDIS_PORT: "{{ config_values[env].redis_port }}"
        KAFKA_BROKERS: "{{ config_values.kafka_brokers }}"
        KAFKA_TOPIC_PREFIX: "{{ config_values[env].kafka_topic_prefix }}"
        SCHEMA_REGISTRY: "{{ config_values.schema_registry_url }}"
        SPA_SITE_RENDERER: "{{ config_values.spa_renderer_url }}"
        FALLBACK_API_URL: "{{ config_values[env].fallback_api_url }}"
      secrets:
        DATABASE_USER: "{{ secrets.database_user }}"
        DATABASE_PASSWORD: "{{ secrets.database_password }}"
        REDIS_PASSWORD: "{{ secrets.redis_password }}"
        FALLBACK_API_BEARER_TOKEN: "{{ secrets.fallback_api_admin_token }}"
    batch:
      config_values:
        VIDEO_FOLDER: "{{ config_values.video_folder }}"
        OTHER_VIDEO_FOLDERS: "{{ config_values.other_video_folders }}"
        IMAGE_FOLDER: "{{ config_values.image_folder }}"
        DATABASE_URL: "{{ config_values[env].database_jdbc_url }}"
        KAFKA_BROKERS: "{{ config_values.kafka_brokers }}"
        KAFKA_TOPIC_PREFIX: "{{ config_values[env].kafka_topic_prefix }}"
        SCHEMA_REGISTRY: "{{ config_values.schema_registry_url }}"
        SPA_SITE_RENDERER: "{{ config_values.spa_renderer_url }}"
      secrets:
        DATABASE_USER: "{{ secrets.database_user }}"
        DATABASE_PASSWORD: "{{ secrets.database_password }}"
        REDIS_PASSWORD: "{{ secrets.redis_password }}"
    db_migration:
      config_values:
        DATABASE_URL: "{{ config_values[env].database_jdbc_url }}"
      secrets:
        DATABASE_USER: "{{ secrets.database_user }}"
        DATABASE_PASSWORD: "{{ secrets.database_password }}"
        HASHED_ADMIN_PASSWORD: "{{ secrets.api_hashed_password }}"
    db_backup:
      config_values:
        DATABASE_URL: "{{ config_values[env].database_url }}"
      secrets:
        DATABASE_USER: "{{ secrets.database_user }}"
        DATABASE_PASSWORD: "{{ secrets.database_password }}"
        AWS_ACCESS_KEY_ID: "{{ secrets.aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ secrets.aws_secret_access_key }}"