- name: Gather git information
  import_tasks: tasks/git-info.yml

- name: Create output directory
  file:
    path: k8s-output
    state: directory

- name: Create K8s config file
  copy:
    dest: k8s-output/kubeconfig
    content: "{{ lookup('aws_ssm', '/infrastructure/prod/k8s/config' if env == 'production' else '/infrastructure/dev/k8s/config', region='ap-southeast-2') }}"