- name: Create output directories
  block:
    - name: Delete existing output directory
      file:
        path: k8s-output
        state: absent

    - name: Create main output directory
      file:
        path: k8s-output
        state: directory

    - name: Create output directory - pgadmin
      file:
        path: k8s-output/pgadmin
        state: directory

    - name: Create output directory - Confluent control center
      file:
        path: k8s-output/confluent
        state: directory

    - name: Create output directory - DB migration
      file:
        path: k8s-output/db-migration
        state: directory

    - name: Create output directory - api
      file:
        path: k8s-output/api
        state: directory

    - name: Create output directory - batch
      file:
        path: k8s-output/batch
        state: directory

- name: Gather git information
  import_tasks: tasks/git-info.yml

- name: Set config values and secrets
  import_tasks: tasks/configs-and-secrets.yml

- name: Render K8s resource files
  block:
    - name: Render K8s common resource files
      template:
        src: "{{ item }}"
        dest: k8s-output/{{ item | basename }}
      with_fileglob:
        - k8s/*.yaml

    - name: Render K8s resource files - pgadmin
      template:
        src: "{{ item }}"
        dest: k8s-output/pgadmin/{{ item | basename }}
      with_fileglob:
        - k8s/pgadmin/*.yaml

    - name: Render K8s resource files - Confluent control center
      template:
        src: "{{ item }}"
        dest: k8s-output/confluent/{{ item | basename }}
      with_fileglob:
        - k8s/confluent-control-center/*.yaml

    - name: Render K8s resource files - DB migration
      template:
        src: "{{ item }}"
        dest: k8s-output/db-migration/{{ item | basename }}
      with_fileglob:
        - k8s/db-migration/*.yaml

    - name: Render K8s resource files - api
      template:
        src: "{{ item }}"
        dest: k8s-output/api/{{ item | basename }}
      with_fileglob:
        - k8s/api/*.yaml

    - name: Render K8s resource files - batch
      template:
        src: "{{ item }}"
        dest: k8s-output/batch/{{ item | basename }}
      with_fileglob:
        - k8s/batch/*.yaml