apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: pgadmin-certificate
  namespace: {{ namespace }}
spec:
  secretName: pgadmin-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ pgadmin_hostname }}