apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: {{ namespace }}
spec:
  tls:
    - secretName: pgadmin-tls-secret
      hosts:
        - {{ pgadmin_hostname }}
  rules:
    - host: {{ pgadmin_hostname }}
      http:
        paths:
          - backend:
              serviceName: pgadmin-service
              servicePort: http-port