apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: {{ namespace }}
spec:
  tls:
    - secretName: pgadmin-tls-secret
      hosts:
        - {{ pgadmin_hostname }}
  rules:
    - host: {{ pgadmin_hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: pgadmin-service
                port:
                  name: http-port