apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
  namespace: {{ namespace }}
type: Opaque
stringData:
{% for key, value in pgadmin.secrets.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}