apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: {{ namespace }}
spec:
  selector:
    app: pgadmin
    branch: {{ git_branch }}
  ports:
    - name: http-port
      port: 80