apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-fast-data-config-map
  namespace: {{ namespace }}
data:
{% for key, value in kafka_fast_data.config_values.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}
