apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-fast-data-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: kafka-fast-data
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-fast-data
        branch: {{ git_branch }}
    spec:
      containers:
        - name: kafka-fast-data-container
          image: lensesio/fast-data-dev:2.6
          envFrom:
            - configMapRef:
                name: kafka-fast-data-config-map
            - secretRef:
                name: kafka-fast-data-secrets
          ports:
            - name: ui-port
              containerPort: 3030
            - name: broker-port
              containerPort: 9092
            - name: registry-port
              containerPort: 8081
