apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-fast-data-ingress
  namespace: {{ namespace }}
spec:
  tls:
    - secretName: kafka-fast-data-tls-secret
      hosts:
        - {{ kafka_fast_data_hostname }}
  rules:
    - host: {{ kafka_fast_data_hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: kafka-fast-data-service
                port:
                  name: ui-port
