apiVersion: v1
kind: Secret
metadata:
  name: kafka-fast-data-secrets
  namespace: {{ namespace }}
type: Opaque
stringData:
{% for key, value in kafka_fast_data.secrets.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}