apiVersion: v1
kind: Service
metadata:
  name: kafka-fast-data-service
  namespace: {{ namespace }}
spec:
  selector:
    app: kafka-fast-data
    branch: {{ git_branch }}
  ports:
    - name: ui-port
      port: 3030
    - name: kafka-broker-port
      port: 9092
    - name: schema-registry-port
      port: 8081