apiVersion: v1
kind: ConfigMap
metadata:
  name: db-backup-config-map
  namespace: {{ namespace }}
data:
{% for key, value in db_backup.config_values.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}