apiVersion: v1
kind: Secret
metadata:
  name: db-backup-secrets
  namespace: {{ namespace }}
type: Opaque
stringData:
{% for key, value in db_backup.secrets.items() %}
  {{ key }}: "{{ value }}"
{% endfor%}
