---
- import_playbook: git-info.yml

- hosts: localhost
  connection: local

  vars_prompt:
    - name: app_name
      prompt: Name of the application?

  tasks:
    - name: Create output directory
      file:
        path: output
        state: directory

    - name: Clean and build sbt project
      shell: cd ../ && sbt cleanAll {{ app_name }}/universal:packageZipTarball

    - name: Generate the Dockerfile
      template:
        src: docker/Dockerfile.j2
        dest: output/Dockerfile-{{ app_name }}
      vars:
        build_timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: Build Web Docker image
      shell: |
        docker build \
          -f output/Dockerfile-{{ app_name }} \
          -t video-downloader-{{ app_name }}:latest \
          -t video-downloader-{{ app_name }}:{{ git_commit }} \
          -t video-downloader-{{ app_name }}:{{ git_branch }}-{{ ansible_date_time.iso8601_basic_short }} \
          ../{{ app_name }}/target/universal/

    - name: Delete output directory
      file:
        path: output
        state: absent