---
- hosts: localhost
  connection: local

  tasks:
    - name: Clean and build sbt projects
      shell: cd ../ && sbt refreshAll

    - name: Build production Web application
      shell: cd ../ && sbt web/universal:packageZipTarball

    - name: Build Web Docker image
      shell: |
        docker build \
          -f docker/Dockerfile-prod-web \
          -t video-downloader-web \
          ../

    - name: Build production Batch application
      shell: cd ../ && sbt batch/universal:packageZipTarball

    - name: Build Batch Docker image
      shell: |
        docker build \
          -f docker/Dockerfile-prod-batch \
          -t video-downloader-batch \
          ../

