---
- hosts: localhost
  connection: local

  vars:
    docker_registry: localhost:32000

  tasks:
    - name: Create output directories
      block:
        - name: Delete existing output directory
          file:
            path: k8s-output
            state: absent

        - name: Create main output directory
          file:
            path: k8s-output
            state: directory

        - name: Create output directory - web
          file:
            path: k8s-output/web
            state: directory

        - name: Create output directory - batch
          file:
            path: k8s-output/batch
            state: directory

    - name: Gather git information
      import_tasks: tasks/git-info.yml

    - name: Render K8s resource files
      block:
        - name: Render K8s Namespace resource file
          template:
            src: k8s/Namespace.yaml
            dest: k8s-output/Namespace.yaml

        - name: Render K8s resource files - web
          template:
            src: "{{ item }}"
            dest: k8s-output/web/{{ item | basename }}
          with_fileglob:
            - k8s/web/*.yaml

        - name: Render K8s resource files - batch
          template:
            src: "{{ item }}"
            dest: k8s-output/batch/{{ item | basename }}
          with_fileglob:
            - k8s/batch/*.yaml

#    - name: Clean up output directory
#      file:
#        path: k8s-output
#        state: absent
