---
- hosts: localhost
  connection: local
  vars:
    KUBECONFIG: /Users/ruchira/Development/k8s-config/ubuntu-vm.yaml

  tasks:
    - name: Gather git information
      import_tasks: tasks/git-info.yml

    - name: Set config values and secrets
      import_tasks: tasks/configs-and-secrets.yml

    - name: Add Bitnami Helm charts repository
      command: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Install Postgres helm chart
      shell: |
        KUBECONFIG={{ KUBECONFIG }} helm install postgresql \
          --set postgresqlUsername="{{ secrets.common.DATABASE_USER }}" \
          --set postgresqlPassword="{{ secrets.common.DATABASE_PASSWORD }}" \
          --set postgresqlDatabase=video-downloader \
          --namespace video-downloader-api-{{ git_branch }} \
          --create-namespace \
          bitnami/postgresql