apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: batch
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: batch
        branch: {{ git_branch }}
    spec:
      containers:
        - name: batch-container
          image: ruchira088/video-downloader-batch:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: batch-data-config-map
            - secretRef:
                name: batch-secrets
          volumeMounts:
            - mountPath: /opt/data
              name: file-config-map
{% for path_mapping in host_path_mappings %}
            - mountPath: {{ path_mapping.pod_mount_path }}
              name: path-mapping-{{ loop.index }}
{% endfor %}
      volumes:
        - name: file-config-map
          configMap:
            name: batch-file-config-map
{% for path_mapping in host_path_mappings %}
        - name: path-mapping-{{ loop.index }}
          hostPath:
            path: {{ path_mapping.host_path }}
            type: Directory
{% endfor %}