apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-deployment
  namespace: video-downloader-back-end-{{ git_branch }}
spec:
  selector:
    matchLabels:
      app: batch
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: batch
        branch: {{ git_branch }}
    spec:
      containers:
        - name: batch-container
          image: ruchira088/video-downloader-batch:{{ git_commit }}
          envFrom:
            - configMapRef:
                name: batch-config-map
            - secretRef:
                name: batch-secrets
          volumeMounts:
            - mountPath: {{ batch.config_values.VIDEO_FOLDER }}
              name: video-folder
            - mountPath: {{ batch.config_values.IMAGE_FOLDER }}
              name: image-folder
      volumes:
        - name: video-folder
          hostPath:
            path: {{ host_video_folder }}
            type: Directory
        - name: image-folder
          hostPath:
            path: {{ host_image_folder }}
            type: Directory