- set_fact:
    config_values:
      common:
        VIDEO_FOLDER: /home/videos
        IMAGE_FOLDER: /home/images
        DATABASE_URL: jdbc:postgresql://postgresql:5432/video-downloader
    secrets:
      common:
        DATABASE_USER: "{{ lookup('aws_ssm', '/video-downloader/' + git_branch + '/database/user', region='ap-southeast-2', aws_profile='personal') }}"
        DATABASE_PASSWORD: "{{ lookup('aws_ssm', '/video-downloader/' + git_branch + '/database/password', region='ap-southeast-2', aws_profile='personal') }}"