apiVersion: v1
kind: ConfigMap
metadata:
  name: db-migration-config-map
  namespace: {{ namespace }}
data:
{% for key, value in db_migration.config_values.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}
