apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job-{{ git_commit }}
  namespace: {{ namespace }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: docker-registry-credentials
      containers:
        - name: database-migration-container
          image: ghcr.io/ruchira088/video-downloader-migration-application:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: db-migration-config-map
            - secretRef:
                name: db-migration-secrets
