apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job-{{ git_commit }}
  namespace: video-downloader-back-end-{{ git_branch }}
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: database-migration-containter
          image: ruchira088/video-downloader-migration-application:{{ git_commit }}
          envFrom:
            - configMapRef:
                name: db-migration-config-map
            - secretRef:
                name: db-migration-secrets
