apiVersion: v1
kind: Secret
metadata:
  name: db-migration-secrets
  namespace: {{ namespace }}
type: Opaque
stringData:
{% for key, value in db_migration.secrets.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}