apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config-map
  namespace: video-downloader-back-end-{{ git_branch }}
data:
{% for key, value in api.config_values.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}
