apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: video-downloader-back-end-{{ git_branch }}
spec:
  selector:
    matchLabels:
      app: api
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        branch: {{ git_branch }}
    spec:
      containers:
        - name: api-container
          image: ruchira088/video-downloader-api:{{ git_commit }}
          envFrom:
            - configMapRef:
                name: api-config-map
            - secretRef:
                name: api-secrets
          readinessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-liveness-probe
          startupProbe:
            periodSeconds: 5
            failureThreshold: 10
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-startup-probe
          ports:
            - name: http4s-port
              containerPort: 8000
          volumeMounts:
            - mountPath: {{ api.config_values.VIDEO_FOLDER }}
              name: video-folder
            - mountPath: {{ api.config_values.IMAGE_FOLDER }}
              name: image-folder
      volumes:
        - name: video-folder
          hostPath:
            path: {{ host_video_folder }}
            type: Directory
        - name: image-folder
          hostPath:
            path: {{ host_image_folder }}
            type: Directory
