apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: {{ namespace }}
spec:
  tls:
    - secretName: api-tls-secret
      hosts:
        - {{ hostname }}
  rules:
    - host: {{ hostname }}
      http:
        paths:
          - backend:
              serviceName: api-service
              servicePort: http4s-port