apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: video-downloader-back-end-{{ git_branch }}
type: Opaque
stringData:
{% for key, value in api.secrets.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}