apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: video-downloader-back-end-{{ git_branch }}
spec:
  selector:
    app: api
    branch: {{ git_branch }}
  ports:
    - name: http4s-port
      port: 8000