---
- hosts: localhost
  connection: local

  vars:
    application: "{{ app }}"

  tasks:
    - name: Install dependencies
      import_tasks: tasks/install-dependencies.yml

    - name: Build & publish Migration Docker image
      when: application == "migration"
      import_tasks: tasks/build-and-publish-scala-docker-image.yml
      vars:
        sbt_project: migrationApplication
        app_name: migration-application
        docker_file: Dockerfile-migration.j2
        publish: true

    - name: Build & publish API Docker image
      when: application == "api"
      import_tasks: tasks/build-and-publish-scala-docker-image.yml
      vars:
        sbt_project: api
        app_name: api
        ports: 8000
        docker_file: Dockerfile.j2
        publish: true

    - name: Build & publish Batch Docker image
      when: application == "batch"
      import_tasks: tasks/build-and-publish-scala-docker-image.yml
      vars:
        sbt_project: batch
        app_name: batch
        docker_file: Dockerfile.j2
        publish: true

    - name: Build & publish DB backup Docker image
      when: application == "db-backup"
      import_tasks: tasks/build-and-publish-db-operation-docker-image.yml
      vars:
        db_operation: backup
        publish: true

    - name: Build & publish DB restore Docker image
      when: application == "db-restore"
      import_tasks: tasks/build-and-publish-db-operation-docker-image.yml
      vars:
        db_operation: restore
        publish: true
