---
- hosts: localhost
  connection: local

  tasks:
    - name: Login to GitHub container registry
      command: docker login ghcr.io -u USERNAME -p {{ access_token }}
      vars:
        access_token: "{{ lookup('aws_ssm', '/github/token', region='ap-southeast-2') }}"

    - name: Build base Scala image
      command: |
        docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          --no-cache \
          -t ghcr.io/ruchira088/video-downloader-scala-base:latest \
          -t ghcr.io/ruchira088/video-downloader-scala-base:version-{{ ansible_date_time.date }} \
          -f docker/base/Dockerfile .

    - name: Build base DB backup image
      command: |
        docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          --no-cache \
          -t ghcr.io/ruchira088/video-downloader-db-backup-base:latest \
          -t ghcr.io/ruchira088/video-downloader-db-backup-base:version-{{ ansible_date_time.date }} \
          -f docker/base/Dockerfile-db-backup .