---
- hosts: localhost
  connection: local

  tasks:
    - name: Install dependencies
      import_tasks: tasks/install-dependencies.yml

    - name: Build & publish Docker images
      import_tasks: tasks/build-and-publish-docker-images.yml
      vars:
        publish: true