---
- hosts: localhost
  connection: local

  tasks:
    - name: Gather git information
      import_tasks: tasks/git-info.yml

    - name: Install dependencies
      import_tasks: tasks/install-dependencies.yml

    - name: Set config values and secrets
      import_tasks: tasks/configs-and-secrets.yml

    - set_fact:
        k8s_vars:
          production:
            namespace: video-downloader-back-end
            hostname: api.video.home.ruchij.com
            host_path_mappings:
              - host_path: /media/data/video-downloader/production/videos
                pod_mount_path: /home/videos
              - host_path: /home/ruchira/Data/video-downloader/production/images
                pod_mount_path: /home/images
          development:
            namespace: video-downloader-back-end-{{ git_branch }}
            hostname: api.{{ git_branch }}.video.dev.ruchij.com
            host_path_mappings:
              - host_path: /media/data/video-downloader/development/videos
                pod_mount_path: /home/videos
              - host_path: /home/ruchira/Data/video-downloader/development/images
                pod_mount_path: /home/images

    - set_fact:
        namespace: "{{ k8s_vars[env].namespace }}"
        hostname: "{{ k8s_vars[env].hostname }}"
        host_path_mappings: "{{ k8s_vars[env].host_path_mappings }}"
        ghcr_credentials: "{{ lookup('aws_ssm', '/github/ghcr/docker-config', region='ap-southeast-2') }}"

    - name: Render K8s resource files
      import_tasks: tasks/k8s-resource-files.yml

    - name: Set kube_config
      import_tasks: tasks/k8s-config.yml

    - name: Deploy K8s resources
      block:
        - name: Create Namespace
          command: kubectl apply -f k8s-output/Namespace.yaml --kubeconfig {{ kubeconfig }}

        - name: Create Docker registry secret
          command: kubectl apply -f k8s-output/DockerRegistryCredentials.yaml --kubeconfig {{ kubeconfig }}

#        - name: Deploy Helm charts
#          block:
#            - name: Add Bitnami Helm charts repository
#              command: helm repo add bitnami https://charts.bitnami.com/bitnami
#
#            - name: Update Helm repositories
#              command: helm repo update
#
#            - name: Deploy PostgreSQL
#              block:
#                - name: Check Postgresql service in K8s
#                  k8s_info:
#                    kind: Service
#                    namespace: "{{ namespace }}"
#                    name: postgresql
#                    kubeconfig: "{{ kubeconfig }}"
#                  register: postgresql_output
#
#                - name: Install Postgres Helm chart
#                  shell: |
#                    KUBECONFIG={{ kubeconfig }} \
#                      helm install postgresql \
#                        --set global.postgresql.auth.username="{{ secrets.database_user }}" \
#                        --set global.postgresql.auth.password="{{ secrets.database_password }}" \
#                        --set global.postgresql.auth.database=video-downloader \
#                        --set image.tag=15.1.0-debian-11-r12 \
#                        --namespace {{ namespace }} \
#                        bitnami/postgresql
#                  when: postgresql_output.resources | length == 0
#
#            - name: Deploy Redis
#              block:
#                - name: Check Redis service in K8s
#                  k8s_info:
#                    kind: Service
#                    namespace: "{{ namespace }}"
#                    name: redis-master
#                    kubeconfig: "{{ kubeconfig }}"
#                  register: redis_output
#
#                - name: Install Redis Helm chart
#                  shell: |
#                    KUBECONFIG={{ kubeconfig }} \
#                      helm install redis \
#                        --set auth.password="{{ secrets.redis_password }}" \
#                        --set architecture=standalone \
#                        --set image.tag=7.0.8 \
#                        --namespace {{ namespace }} \
#                        bitnami/redis
#                  when: redis_output.resources | length == 0
#
#            - name: Deploy Kafka & Schema Registry
#              block:
#                - name: Check Confluent service in K8s
#                  k8s_info:
#                    kind: Service
#                    namespace: "{{ namespace }}"
#                    name: confluent-kafka
#                    kubeconfig: "{{ kubeconfig }}"
#                  register: confluent_output
#
#                - name: Install Confluent Helm chart
#                  shell: |
#                    KUBECONFIG={{ kubeconfig }} \
#                      helm install confluent \
#                        --set image.tag=7.3.2-debian-11-r0 \
#                        --namespace {{ namespace }} \
#                        bitnami/schema-registry
#                  when: confluent_output.resources | length == 0

        - name: Deploy DB backup
          block:
            - name: Create ConfigMap
              command: kubectl apply -f k8s-output/db-backup/ConfigMap.yaml --kubeconfig {{ kubeconfig }}

            - name: Create Secrets
              command: kubectl apply -f k8s-output/db-backup/Secrets.yaml --kubeconfig {{ kubeconfig }}

            - name: Deploy CronJob
              command: kubectl apply -f k8s-output/db-backup --kubeconfig {{ kubeconfig }}

            - name: Take DB backup snapshot
              block:
                - name: Set DB snapshot job name
                  set_fact:
                    snapshot_job_name: db-backup-job-{{ git_commit }}-{{ ansible_date_time.iso8601_basic_short | lower }}

                - name: Run DB backup job
                  command: |
                    kubectl create job \
                      --from=cronjob/db-backup-cron-job \
                      {{ snapshot_job_name }} \
                      --kubeconfig {{ kubeconfig }} \
                      -n {{ namespace }}

                - name: Wait for DB backup snapshot to complete
                  command: |
                    kubectl wait \
                      --for=condition=complete \
                      job/{{ snapshot_job_name }} \
                      --kubeconfig {{ kubeconfig }} \
                      -n {{ namespace }} \
                      --timeout=120s

        - name: Deploy DB migration
          block:
            - name: Create ConfigMap
              command: kubectl apply -f k8s-output/db-migration/ConfigMap.yaml --kubeconfig {{ kubeconfig }}

            - name: Create Secrets
              command: kubectl apply -f k8s-output/db-migration/Secrets.yaml --kubeconfig {{ kubeconfig }}

            - name: Deploy Job
              command: kubectl apply -f k8s-output/db-migration --kubeconfig {{ kubeconfig }}

            - name: Wait Job to complete
              command: |
                kubectl wait \
                  --for=condition=complete \
                  job/database-migration-job-{{ git_commit }} \
                  --kubeconfig {{ kubeconfig }} \
                  -n {{ namespace }} \
                  --timeout=120s

        - name: Deploy api
          block:
            - name: Create data ConfigMap
              command: kubectl apply -f k8s-output/api/DataConfigMap.yaml --kubeconfig {{ kubeconfig }}

            - name: Create file ConfigMap
              command: kubectl apply -f k8s-output/api/FileConfigMap.yaml --kubeconfig {{ kubeconfig }}

            - name: Create Secrets
              command: kubectl apply -f k8s-output/api/Secrets.yaml --kubeconfig {{ kubeconfig }}

            - name: Deploy application
              command: kubectl apply -f k8s-output/api --kubeconfig {{ kubeconfig }}

        - name: Deploy batch
          block:
            - name: Create data ConfigMap
              command: kubectl apply -f k8s-output/batch/DataConfigMap.yaml --kubeconfig {{ kubeconfig }}

            - name: Create file ConfigMap
              command: kubectl apply -f k8s-output/batch/FileConfigMap.yaml --kubeconfig {{ kubeconfig }}

            - name: Create Secrets
              command: kubectl apply -f k8s-output/batch/Secrets.yaml --kubeconfig {{ kubeconfig }}

            - name: Deploy application
              command: kubectl apply -f k8s-output/batch --kubeconfig {{ kubeconfig }}

        - name: Wait for successful api deployment
          command: kubectl rollout status deployment api-deployment --kubeconfig {{ kubeconfig }} -n {{ namespace }}

        - name: Wait for successful batch deployment
          command: kubectl rollout status deployment batch-deployment --kubeconfig {{ kubeconfig }} -n {{ namespace }}

    - name: Clean up output directory
      file:
        path: k8s-output
        state: absent