---
- hosts: localhost
  connection: local

  tasks:
    - name: Gather git information
      import_tasks: tasks/git-info.yml

    - name: Set config values and secrets
      import_tasks: tasks/configs-and-secrets.yml

    - name: Set kube_config
      import_tasks: tasks/k8s-config.yml

    - name: Add Bitnami Helm charts repository
      command: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Install Postgres helm chart
      shell: |
        KUBECONFIG={{ kube_config }} helm install postgresql \
          --set postgresqlUsername="{{ secrets.database_user }}" \
          --set postgresqlPassword="{{ secrets.database_password }}" \
          --set postgresqlDatabase=video-downloader \
          --namespace video-downloader-api-{{ git_branch }} \
          --create-namespace \
          bitnami/postgresql