name: Backend - Deploy To K8s

on: workflow_call

jobs:
  deploy-to-k8s:
    name: Deploy to K8s
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to K8s server
        run: ansible-playbook -vvv playbooks/k8s-deploy.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}