name: Backend Daily Pipeline

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  compile-and-test:
    name: Run test suite
    uses: ./.github/workflows/jobs/backend-test.yml
    secrets: inherit

  send-notification:
    name: Send Slack notification
    runs-on: ubuntu-latest
    if: always()

    permissions:
      id-token: write

    needs:
      - compile-and-test

    steps:
      - name: Send Slack notification
        uses: ruchira088/slack-github-action@v1