name: Backend Pipeline

on:
  push:
    branches:
      - "**"

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-and-test:
    name: Run test suite
    uses: ./.github/workflows/backend-test.yml
    secrets: inherit

  publish-docker-images:
    name: Publish Docker images
    uses: ./.github/workflows/backend-publish.yml
    secrets: inherit
    needs:
      - compile-and-test

  deploy-to-k8s:
    name: Backend deploy to K8s
    uses: ./.github/workflows/backend-deploy.yml
    secrets: inherit
    needs:
      - publish-docker-images

  send-notification:
    runs-on: ubuntu-latest
    if: always()

    permissions:
      id-token: write

    needs:
      - compile-and-test
      - publish-docker-images
      - deploy-to-k8s

    steps:
      - name: Send Slack notification
        uses: ruchira088/slack-github-action@v1
