name: Backend - Compile & Test

on: workflow_call

jobs:
  compile-and-test:
    name: Compile & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/Dependencies.scala') }}
          path: |
            ~/.sbt
            ~/.cache/coursier
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}
            ${{ runner.os }}-${{ hashFiles('**/build.properties') }}
            ${{ runner.os }}

      - name: Fetch compile dependencies
        run: sbt update

      - name: Compile
        run: sbt compile

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install ffmpeg -y

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Fetch test dependencies
        run: sbt "Test / update"

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u USERNAME -p ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Execute test suite
        run: sbt test