name: Fallback API Pipeline

on:
  push:
    branches:
      - "**"

concurrency:
  group: fallback-api-job-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./fallback-api

jobs:
  execute-test-suite:
    name: Execute test suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check formatting
        run: ruff format --check

      - name: Check linting
        run: ruff check

      - name: Execute test suite
        run: python -m unittest -v

  send-notification:
    name: Send Slack notification
    runs-on: ubuntu-latest
    if: always()

    permissions:
      id-token: write

    needs:
      - execute-test-suite

    steps:
      - name: Send Slack notification
        uses: ruchira088/slack-github-action@v1


