name: Fallback API

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-fallback-api:
    uses: ./fallback-api/.github/workflows/build-pipeline.yml
    secrets: inherit