name: Fallback API Pipeline

on:
  push:
    branches:
      - "**"

concurrency:
  group: fallback-api-job-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run Fallback API tests
    uses: ./.github/workflows/fallback-api-test.yml
    secrets: inherit

  send-notification:
    runs-on: ubuntu-latest
    if: always()

    permissions:
      id-token: write

    needs:
      - run-tests

    steps:
      - name: Send Slack notification
        uses: ruchira088/slack-github-action@v1