name: Send Slack Notification

on:
  workflow_call:
    inputs:
      message:
        type: string
        required: true

jobs:
  send-slack-notification:
    name: Send Slack notification
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack message
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: C02HYP398KS
          slack-message: |
            ${{ inputs.message }}
            *${{ github.repository }}*
            *Branch:* ${{ github.ref }}
            *Commit:* `${{ github.sha }}`
            *URL:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}